Use /bin/sh and printf to silence linter errors

diff --git a/buildroot-external/rootfs-overlay/usr/sbin/hassos-cli b/buildroot-external/rootfs-overlay/usr/sbin/hassos-cli
--- a/buildroot-external/rootfs-overlay/usr/sbin/hassos-cli
+++ b/buildroot-external/rootfs-overlay/usr/sbin/hassos-cli
@@ -1,12 +1,12 @@
-#!/bin/ash
+#!/bin/sh
 # ==============================================================================
 # Run logging cli
 # ==============================================================================
 
 run_shell() { exec /bin/ash -l; }
-interrupt() { echo -e " cancelled"; systemctl reset-failed "ha-cli@*"; run_shell; }
+interrupt() { echo " cancelled"; systemctl reset-failed "ha-cli@*"; run_shell; }
 emergency_shell() {
-    echo -e "\n\n[WARNING] Home Assistant CLI is not starting or was interrupted."
+    printf "\n\n[WARNING] Home Assistant CLI is not starting or was interrupted.\n"
     echo ""
     echo "This happens when start of all services takes longer than expected, or because"
     echo "of slow internet connection. Emergency console has been started, you can use"
@@ -21,16 +21,16 @@ emergency_shell() {
 
 trap interrupt INT
 
-echo -n "Waiting for the Home Assistant CLI to be ready..."
+printf "Waiting for the Home Assistant CLI to be ready..."
 
 i=0
 while [ ! "$(docker ps -q -f name=hassio_cli)" ]; do
     sleep 1
 
     if [ $((i % 4)) = 0 ]; then
-        echo -ne "\010\010\010   \010\010\010"
+        printf "\010\010\010   \010\010\010"
     else
-        echo -n "."
+        printf "."
     fi
 
     i=$((i+1))
@@ -51,16 +51,16 @@ case $? in
     ;;
   130)
     # 130 is CLI termination with Ctrl+C (SIGINT)
-    echo -e "\nHome Assistant CLI has been interrupted."
+    printf "\nHome Assistant CLI has been interrupted.\n"
     systemctl reset-failed "ha-cli@*"
     ;;
   143)
     # 143 graceful termination (SIGTERM). Most likely a proper shutdown.
     # Just sleep for a while until actual systemd shutdown gets invoked.
-    echo -e "\nHome Assistant CLI has been terminated."
+    printf "\nHome Assistant CLI has been terminated.\n"
     sleep 30
     ;;
   *)
-    echo -e "\nHA CLI failed with error code: $?"
+    printf "\nHA CLI failed with error code: %s\n" "$?"
     ;;
 esac
