Avoid waiting for external drive unnecessarily
Even though the condition to start hassos-data.service is not met (the
file /mnt/overlay/data-move is not there by default), it seems that
systemd waits for the dependencies for hassos-data.service. Don't
Require or Wants any dependencies which might not be present. Make sure
to check in the script that dependencies are present.

diff --git a/buildroot-external/rootfs-overlay/usr/libexec/hassos-data b/buildroot-external/rootfs-overlay/usr/libexec/hassos-data
--- a/buildroot-external/rootfs-overlay/usr/libexec/hassos-data
+++ b/buildroot-external/rootfs-overlay/usr/libexec/hassos-data
@@ -7,8 +7,18 @@ set -e
 # Rely on systemd-udev symlinks to find current data partition by fs label
 OLD_DEVICE_CHILD="$(readlink -f "/dev/disk/by-label/hassos-data")"
 
+NEW_DEVICE="/dev/disk/by-partlabel/hassos-data-external"
+
+# The device should be ready by now guaranteed by systemd Wants/After,
+# but in case the user unplugged the device, this service still gets started.
+# Exit with an error in this case.
+if [ ! -e "${NEW_DEVICE}" ]; then
+    echo "[ERROR] External data device ${NEW_DEVICE} not found!"
+    exit 1
+fi
+
 # Rely on systemd-udev symlinks to find external data partition by partlabel
-NEW_DEVICE_CHILD="$(readlink -f "/dev/disk/by-partlabel/hassos-data-external")"
+NEW_DEVICE_CHILD="$(readlink -f "${NEW_DEVICE}")"
 
 NEW_DEVICE_PART_SIZE=$(cat "/sys/class/block/$(basename "${NEW_DEVICE_CHILD}")/size")
 OLD_DEVICE_PART_SIZE=$(cat "/sys/class/block/$(basename "${OLD_DEVICE_CHILD}")/size")
