Avoid waiting for external drive unnecessarily (#1066)
* Avoid waiting for external drive unnecessarily

Even though the condition to start hassos-data.service is not met (the
file /mnt/overlay/data-move is not there by default), it seems that
systemd waits for the dependencies for hassos-data.service. Don't
Require or Wants any dependencies which might not be present by
default.

* Use systemd to wait for partition using partlabel device

* Use sfdisk which allows to wipe filesystem signatures

Even though we zap the partition table using sgdisk, the file system
superblock (which contains the file system label) does survive. This
can cause problems when trying to reuse a disk previously already
labeled using hassos-data: It might take precendence on next boot
over the existing data partition on the eMMC.

Make sure to clean all file system signatures using sfdisk.

diff --git a/buildroot-external/rootfs-overlay/usr/libexec/hassos-data b/buildroot-external/rootfs-overlay/usr/libexec/hassos-data
--- a/buildroot-external/rootfs-overlay/usr/libexec/hassos-data
+++ b/buildroot-external/rootfs-overlay/usr/libexec/hassos-data
@@ -7,6 +7,16 @@ set -e
 # Rely on systemd-udev symlinks to find current data partition by fs label
 OLD_DEVICE_CHILD="$(readlink -f "/dev/disk/by-label/hassos-data")"
 
+# We cannot rely on systemd Wants/Requires since this is evaluated before
+# ConditionPathExists, and would make us wait for an external device on
+# every boot.
+# Instead, just start the unit here, which makes sure a device with the
+# partlabel "hassos-data-external" is present.
+if ! systemctl start "dev-disk-by\\x2dpartlabel-hassos\\x2ddata\\x2dexternal.device"; then
+    echo "[ERROR] External data device ${NEW_DEVICE} not found!"
+    exit 1
+fi
+
 # Rely on systemd-udev symlinks to find external data partition by partlabel
 NEW_DEVICE_CHILD="$(readlink -f "/dev/disk/by-partlabel/hassos-data-external")"
 
