Use systemd-growfs (#1133)
* Use systemd-growfs instead of resize2fs (#1106)

Since systemd 236 systemd has a built-in file system growing mechanism.
The mechanism relies on the kernels online file system resize
capabilities instead of the external resize2fs utility. Online resizing
is supposedly much faster since the kernel takes care of things.

This also makes sure that external file systems get resized which
previously have not been taken care of.

* Drop HA OS specific file system resizing

Since we have systemd-growfs in place now we can drop our file system
resizing code.

* Make sure /dev/disk/by-label/hassos-data is present after resizing

Note: systemd will retry mnt-data.mount later, so at least in theory
this shouldn't really matter. However, the journal has a lot of churn
due to that reordering.

diff --git a/buildroot-external/rootfs-overlay/usr/libexec/hassos-expand b/buildroot-external/rootfs-overlay/usr/libexec/hassos-expand
--- a/buildroot-external/rootfs-overlay/usr/libexec/hassos-expand
+++ b/buildroot-external/rootfs-overlay/usr/libexec/hassos-expand
@@ -52,11 +52,17 @@ else
     sfdisk -V "${DEVICE_ROOT}"
 fi
 
+# Reload partition table
 partx -u "${DEVICE_ROOT}"
+udevadm settle
 
-# Resize filesystem
-echo "[INFO] Resize hassos-data filesystem"
-e2fsck -y "${DEVICE_CHILD}"
-resize2fs -f "${DEVICE_CHILD}"
+# Make sure /dev/disk/by-label/hassos-data is actually present before exiting.
+# This avoids a race condition with mnt-data.mount which might fail to bind
+# otherwise:
+# Bound to unit dev-disk-by\x2dlabel-hassos\x2ddata.device, but unit isn't active.
+if ! systemctl start "dev-disk-by\\x2dlabel-hassos\\x2ddata.device"; then
+    echo "[ERROR] Data partition not found!"
+    exit 1
+fi
 
-echo "[INFO] Finish hassos-data resizing"
+echo "[INFO] Finished hassos-data partition resizing"
